# This file is a template, and might need editing before it works on your project.
image: node:10-alpine

# These folders are cached between builds
cache:
  paths:
    - ./node_modules

pages:
  stage: deploy
  before_script:
    - yarn install
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
