backend:
  name: gitlab
  repo: gcutrini/openinfralabs-website
  branch: adds-menu
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "configurations"
    label: "Configurations"
    editor:
      preview: false
    files:
      - file: "src/content/site-metadata.json"
        label: "Site Metadata"
        name: "siteMetadata"
        fields:
          - {label: "Metadata", name: "siteMetadata", widget: "object", fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Title Template", name: "titleTemplate", widget: string},
              {label: "Description", name: "description", widget: string},
              {label: "Url", name: "url", widget: string},
              {label: "Image", name: "image", widget: image},
              {label: "Theme Color", name: "themeColor", widget: string},
          ]} 
      - file: "src/content/top-bar.json"
        label: "Top Bar"
        name: "topBar"
        fields:
          - {label: "Bar Info", name: "topBar", widget: object, fields: [
              {label: "Text", name: "text", widget: string},
              {label: "Link", name: "link", widget: string},
              {label: "Button", name: "button", widget: string},
              {label: "Display", name: "display", widget: boolean}
            ]}

      - file: "src/content/nav-bar.json"
        label: "Nav Bar"
        name: "navBar"
        fields:
          - {label: "Menu Item", name: "navBar", widget: list, fields: [
              {label: "Text", name: "text", widget: string},
              {label: "Link", name: "link", widget: string},
              {label: "Display", name: "display", widget: boolean},
            ]}
      - file: "src/content/blog-config.json"
        label: "Blog Configuration"
        name: "blogConfig"
        fields:
          - {label: "Title", name: "title", widget: string}
          - {label: "Subtitle", name: "subTitle", widget: string}
          - {label: "Categories", name: "categories", widget: list, fields: [
              {label: "Category", name: "text", widget: "string"},
              {label: "ID", name: "id", widget: ncw-id, prefix: category}
            ]}
          - {label: "Links", name: "connect", widget: list, fields: [
              {label: "Text", name: "text", widget: string },
              {label: "Link", name: "link", widget: string },
            ]}
  - name: "index"
    label: "Landing"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: SEO, name: seo, widget: object, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Description", name: "description", widget: string},
              {label: "Url", name: "url", widget: string},
              {label: "Image", name: "image", widget: image},
            ]}
          - {label: Header, name: header, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: Subtitle, name: subTitle, widget: text},
            ]}
          - {label: Intro, name: intro, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: Text, name: text, widget: text}
            ]}
          - {label: Features, name: features, widget: object, fields: [              
              {label: Title, name: title, widget: string},
              {label: Features, name: featureList, widget: list, fields: [
                {label: Title, name: title, widget: string},
                {label: Icon, name: image, widget: image},
                {label: Details, name: details, widget: text},
              ]}
          ]}
          - {label: Sponsors, name: sponsors, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: List, name: sponsorList, widget: list, fields: [
                {label: Sponsor, name: logo, widget: image},
              ]}
          ]}
          - {label: "Body", name: body, widget: markdown}   
  - name: "pages"
    label: "Pages"
    folder: "src/pages/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "custom-page"}
      - {label: SEO, name: seo, widget: object, fields: [
          {label: "Title", name: "title", widget: string},
          {label: "Description", name: "description", widget: string},
          {label: "Url", name: "url", widget: string},
          {label: "Image", name: "image", widget: image},
        ]}
      - {label: Title, name: title, widget: string}
      - {label: "Body", name: body, widget: markdown}
  - name: "authors"
    label: "Authors"
    folder: "/src/pages/author"
    create: true    
    editor:
      preview: false
    identifier_field: authorName
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tags"}
      - {label: "Name", name: authorName, widget: string}
      - {label: "Company", name: company, widget: string}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["authorName"], valueField: "authorName" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: ncw-file-relation, collection: configurations, file: blogConfig, target_field: categories, id_field: id, display_fields: text, required: false }
      - {label: "Body", name: "body", widget: "markdown"}
